name: Update Blog Posts
  

on:
  push:
      branches:
        - main # 또는 워크플로우를 트리거하고 싶은 브랜치 이름
  workflow_dispatch:	# 수동 실행 트리거 추가
  schedule:
    - cron: '0 0 * * *' # 매일 9에 실행

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set time zone
      run: |
        sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
        echo "Asia/Seoul" | sudo tee /etc/timezone
        date

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser gitpython python-dateutil

    - name: Run script
